/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: rtc/rtc.proto */

#ifndef PROTOBUF_C_rtc_2frtc_2eproto__INCLUDED
#define PROTOBUF_C_rtc_2frtc_2eproto__INCLUDED

#include "protobuf-c/protobuf-c.h"

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct Rtc__SignalRequest Rtc__SignalRequest;
typedef struct Rtc__SignalResponse Rtc__SignalResponse;
typedef struct Rtc__RtcConfig Rtc__RtcConfig;
typedef struct Rtc__IceServer Rtc__IceServer;
typedef struct Rtc__SessionDescription Rtc__SessionDescription;
typedef struct Rtc__Subscribe Rtc__Subscribe;
typedef struct Rtc__Subscribe__Media Rtc__Subscribe__Media;
typedef struct Rtc__Subscribe__Options Rtc__Subscribe__Options;
typedef struct Rtc__AddTrack Rtc__AddTrack;
typedef struct Rtc__TrackInfo Rtc__TrackInfo;
typedef struct Rtc__RemoveTrack Rtc__RemoveTrack;
typedef struct Rtc__State Rtc__State;
typedef struct Rtc__States Rtc__States;
typedef struct Rtc__Options Rtc__Options;
typedef struct Rtc__Location Rtc__Location;
typedef struct Rtc__Joined Rtc__Joined;
typedef struct Rtc__Leaved Rtc__Leaved;
typedef struct Rtc__Leave Rtc__Leave;
typedef struct Rtc__Ping Rtc__Ping;
typedef struct Rtc__Pong Rtc__Pong;
typedef struct Rtc__Response Rtc__Response;
typedef struct Rtc__Vad Rtc__Vad;
typedef struct Rtc__Volume Rtc__Volume;
typedef struct Rtc__Broadcast Rtc__Broadcast;
typedef struct Rtc__Mute Rtc__Mute;
typedef struct Rtc__Mute__Media Rtc__Mute__Media;
typedef struct Rtc__PeerInfo Rtc__PeerInfo;
typedef struct Rtc__SrtpKey Rtc__SrtpKey;
typedef struct Rtc__NodeList Rtc__NodeList;
typedef struct Rtc__NodeRtts Rtc__NodeRtts;
typedef struct Rtc__NodeRtt Rtc__NodeRtt;
typedef struct Rtc__SelectChannel Rtc__SelectChannel;
typedef struct Rtc__Stats Rtc__Stats;


/* --- enums --- */

/*
 * ICE 传输策略
 */
typedef enum _Rtc__IcePolicy {
  /*
   * 不设置候选地址，表示由客户端配置候选地址类型，或者让系统采用默认策略（通常是允许所有类型的候选地址）
   */
  RTC__ICE_POLICY__ICE_POLICY_NONE = 0,
  /*
   * 允许所有类型的候选地址（包括 host、srflx、prflx 和 relay）
   */
  RTC__ICE_POLICY__ICE_POLICY_ALL = 1,
  /*
   * 只允许除 host 之外的 srflx、prflx 和 relay 类型的候选地址
   */
  RTC__ICE_POLICY__ICE_POLICY_NO_HOST = 2,
  /*
   * 只允许 relay（TURN 中继）类型的候选地址
   */
  RTC__ICE_POLICY__ICE_POLICY_RELAY = 3,
  /*
   * 只允许 relay（TURN 中继）类型的 UDP 候选地址
   */
  RTC__ICE_POLICY__ICE_POLICY_RELAY_UDP = 4,
  /*
   * 只允许 relay（TURN 中继）类型的 TCP 候选地址
   */
  RTC__ICE_POLICY__ICE_POLICY_RELAY_TCP = 5,
  /*
   * 只允许 relay（TURN 中继）类型的 TLS 候选地址
   */
  RTC__ICE_POLICY__ICE_POLICY_RELAY_TLS = 6
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(RTC__ICE_POLICY)
} Rtc__IcePolicy;
/*
 * SDP 类型，对应 RTCSdpType
 */
typedef enum _Rtc__SdpType {
  /*
   * 未知类型，RTCSdpType 无此项，应该做容错处理
   */
  RTC__SDP_TYPE__SDP_TYPE_UNKNOWN = 0,
  /*
   * RTCSdpType 的 "offer"
   */
  RTC__SDP_TYPE__SDP_TYPE_OFFER = 1,
  /*
   * RTCSdpType 的 "pranswer"
   */
  RTC__SDP_TYPE__SDP_TYPE_PRANSWER = 2,
  /*
   * RTCSdpType 的 "answer"
   */
  RTC__SDP_TYPE__SDP_TYPE_ANSWER = 3,
  /*
   * RTCSdpType 的 "rollback"
   */
  RTC__SDP_TYPE__SDP_TYPE_ROLLBACK = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(RTC__SDP_TYPE)
} Rtc__SdpType;
/*
 * 服务端媒体通道连接状态
 */
typedef enum _Rtc__PeerState {
  /*
   * 未知状态
   */
  RTC__PEER_STATE__PEER_STATE_UNKNOWN = 0,
  /*
   * 新连接
   */
  RTC__PEER_STATE__PEER_STATE_NEW = 1,
  /*
   * 连接中
   */
  RTC__PEER_STATE__PEER_STATE_CONNECTING = 2,
  /*
   * 已连接
   */
  RTC__PEER_STATE__PEER_STATE_CONNECTED = 3,
  /*
   * 断开连接
   */
  RTC__PEER_STATE__PEER_STATE_DISCONNECTED = 4,
  /*
   * 连接失败
   */
  RTC__PEER_STATE__PEER_STATE_FAILED = 5,
  /*
   * 连接关闭
   */
  RTC__PEER_STATE__PEER_STATE_CLOSED = 6
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(RTC__PEER_STATE)
} Rtc__PeerState;
/*
 * 关闭原因
 */
typedef enum _Rtc__CloseReason {
  /*
   * 客户端主动离开，服务端信令通道与媒体通道关闭，应该结束通话
   */
  RTC__CLOSE_REASON__REASON_USER_LEAVE = 0,
  /*
   * 服务端媒体通道等待超时而关闭，应该结束通话
   */
  RTC__CLOSE_REASON__REASON_PEER_TIMEOUT = 1,
  /*
   * 服务端媒体通道关闭，应该结束通话
   */
  RTC__CLOSE_REASON__REASON_PEER_CLOSED = 2,
  /*
   * 服务端房间关闭（例如服务节点关闭时会触发），应该结束通话
   */
  RTC__CLOSE_REASON__REASON_ROOM_CLOSED = 5,
  /*
   * 服务端信令通道被动关闭（例如客户端断网会触发），此时媒体通道可能还在，不应该结束通话
   */
  RTC__CLOSE_REASON__REASON_SIGNAL_CLOSED = 4,
  /*
   * 服务端重新创建媒体通道而关闭旧的，不应该结束通话
   */
  RTC__CLOSE_REASON__REASON_PEER_RECREAT = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(RTC__CLOSE_REASON)
} Rtc__CloseReason;
/*
 * 操作系统类型
 */
typedef enum _Rtc__OsType {
  RTC__OS_TYPE__OS_TYPE_UNKNOWN = 0,
  RTC__OS_TYPE__OS_TYPE_ANDROID = 1,
  RTC__OS_TYPE__OS_TYPE_IOS = 2,
  RTC__OS_TYPE__OS_TYPE_WINDOWS = 3,
  RTC__OS_TYPE__OS_TYPE_MACOS = 4,
  RTC__OS_TYPE__OS_TYPE_LINUX = 5
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(RTC__OS_TYPE)
} Rtc__OsType;
/*
 * SRTP 加密算法
 */
typedef enum _Rtc__SrtpProfile {
  RTC__SRTP_PROFILE__UNKNOWN = 0,
  RTC__SRTP_PROFILE__AES128_CM_HMAC_SHA1_80 = 1,
  RTC__SRTP_PROFILE__AES128_CM_HMAC_SHA1_32 = 2,
  RTC__SRTP_PROFILE__AES256_CM_HMAC_SHA1_80 = 3,
  RTC__SRTP_PROFILE__AES256_CM_HMAC_SHA1_32 = 4,
  RTC__SRTP_PROFILE__NULL_HMAC_SHA1_80 = 5,
  RTC__SRTP_PROFILE__NULL_HMAC_SHA1_32 = 6,
  RTC__SRTP_PROFILE__AEAD_AES_128_GCM = 7,
  RTC__SRTP_PROFILE__AEAD_AES_256_GCM = 8
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(RTC__SRTP_PROFILE)
} Rtc__SrtpProfile;
/*
 * 通道标识
 */
typedef enum _Rtc__Channel {
  RTC__CHANNEL__CHANNEL_SFU = 0,
  RTC__CHANNEL__CHANNEL_MESH = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(RTC__CHANNEL)
} Rtc__Channel;
/*
 * 媒体节点模式
 */
typedef enum _Rtc__Mode {
  /*
   * SFU 模式
   */
  RTC__MODE__MODE_SFU = 0,
  /*
   * Mesh 模式
   */
  RTC__MODE__MODE_MESH = 1,
  /*
   * SFU+Mesh 双模式
   */
  RTC__MODE__MODE_BOTH = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(RTC__MODE)
} Rtc__Mode;
/*
 * 统计信息来源，服务端或客户端
 */
typedef enum _Rtc__Source {
  RTC__SOURCE__SOURCE_SERVER = 0,
  RTC__SOURCE__SOURCE_CLIENT = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(RTC__SOURCE)
} Rtc__Source;
/*
 * 传输方向
 */
typedef enum _Rtc__Direction {
  RTC__DIRECTION__DIRECTION_UNKNOWN = 0,
  RTC__DIRECTION__DIRECTION_UP = 1,
  RTC__DIRECTION__DIRECTION_DOWN = 2,
  RTC__DIRECTION__DIRECTION_BOTH = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(RTC__DIRECTION)
} Rtc__Direction;
/*
 * 协议类型
 */
typedef enum _Rtc__Protocol {
  RTC__PROTOCOL__PROTOCOL_UNKNOWN = 0,
  RTC__PROTOCOL__PROTOCOL_UDP = 1,
  RTC__PROTOCOL__PROTOCOL_TCP = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(RTC__PROTOCOL)
} Rtc__Protocol;
/*
 * 数据类型，1 音频，2～99 视频，100 数据，101 TURN，102 信令
 */
typedef enum _Rtc__DataType {
  RTC__DATA_TYPE__DATA_TYPE_UNKNOWN = 0,
  RTC__DATA_TYPE__DATA_TYPE_OPUS = 1,
  RTC__DATA_TYPE__DATA_TYPE_H264 = 2,
  RTC__DATA_TYPE__DATA_TYPE_H265 = 3,
  RTC__DATA_TYPE__DATA_TYPE_VP8 = 4,
  RTC__DATA_TYPE__DATA_TYPE_VP9 = 5,
  RTC__DATA_TYPE__DATA_TYPE_AV1 = 6,
  RTC__DATA_TYPE__DATA_TYPE_DATACHANNEL = 100,
  RTC__DATA_TYPE__DATA_TYPE_TURN = 101,
  RTC__DATA_TYPE__DATA_TYPE_SIGNAL = 102
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(RTC__DATA_TYPE)
} Rtc__DataType;

/* --- messages --- */

typedef enum {
  RTC__SIGNAL_REQUEST__MESSAGE__NOT_SET = 0,
  RTC__SIGNAL_REQUEST__MESSAGE_JOIN = 2,
  RTC__SIGNAL_REQUEST__MESSAGE_ANSWER = 3,
  RTC__SIGNAL_REQUEST__MESSAGE_CANDIDATE = 4,
  RTC__SIGNAL_REQUEST__MESSAGE_NEGOTIATION = 5,
  RTC__SIGNAL_REQUEST__MESSAGE_SUBSCRIBE = 6,
  RTC__SIGNAL_REQUEST__MESSAGE_RECREATE = 7,
  RTC__SIGNAL_REQUEST__MESSAGE_LEAVE = 8,
  RTC__SIGNAL_REQUEST__MESSAGE_PING = 9,
  RTC__SIGNAL_REQUEST__MESSAGE_STATS = 10,
  RTC__SIGNAL_REQUEST__MESSAGE_BROADCAST = 11,
  RTC__SIGNAL_REQUEST__MESSAGE_ADDR = 12,
  RTC__SIGNAL_REQUEST__MESSAGE_OFFER = 13,
  RTC__SIGNAL_REQUEST__MESSAGE_VAD = 14,
  RTC__SIGNAL_REQUEST__MESSAGE_SRTP_KEY = 15,
  RTC__SIGNAL_REQUEST__MESSAGE_NODE_RTTS = 16,
  RTC__SIGNAL_REQUEST__MESSAGE_MUTE = 17,
  RTC__SIGNAL_REQUEST__MESSAGE_ADD_STATS = 18,
  RTC__SIGNAL_REQUEST__MESSAGE_SELECT_CHANNEL = 20
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(RTC__SIGNAL_REQUEST__MESSAGE__CASE)
} Rtc__SignalRequest__MessageCase;

/*
 * 客户端向服务端发送请求
 */
struct  Rtc__SignalRequest
{
  ProtobufCMessage base;
  /*
   * 客户端请求消息 ID
   */
  uint32_t id;
  /*
   * 通道标识，对于 SFU+Mesh 模式，0=SFU通道，1=Mesh通道
   */
  uint32_t channel;
  Rtc__SignalRequest__MessageCase message_case;
  union {
    /*
     * 客户端获取自己公网 IP
     */
    char *addr;
    /*
     * 客户端 ICE 候选信息（IP、端口等），值是 RTCIceCandidate JSON
     * 编码后的字符串
     */
    char *candidate;
    /*
     * 客户端请求服务端 RTP 统计信息
     */
    char *stats;
    /*
     * 上报客户端统计信息
     */
    Rtc__Stats *add_stats;
    /*
     * 客户端回复 answer 给服务端
     */
    Rtc__SessionDescription *answer;
    /*
     * 客户端向房间广播消息
     */
    Rtc__Broadcast *broadcast;
    /*
     * 客户端加入房间
     */
    Rtc__Options *join;
    /*
     * 客户端离开房间，正常退出务必调用，避免服务端保留媒体通道25秒
     */
    Rtc__Leave *leave;
    /*
     * 上报静音/空帧状态
     */
    Rtc__Mute *mute;
    /*
     * 上报节点 RTT
     */
    Rtc__NodeRtts *node_rtts;
    /*
     * Mesh 向远端发送 offer
     */
    Rtc__SessionDescription *offer;
    /*
     * 客户端发送心跳包
     */
    Rtc__Ping *ping;
    /*
     * 客户端强制要求服务端重新创建媒体连接
     */
    Rtc__Options *recreate;
    /*
     * 选择通道
     */
    Rtc__SelectChannel *select_channel;
    /*
     * Mesh 上报 SRTP Key
     */
    Rtc__SrtpKey *srtp_key;
    /*
     * 客户端订阅/取消订阅音视频 Track
     */
    Rtc__Subscribe *subscribe;
    /*
     * Mesh 向远端发送音量
     */
    Rtc__Vad *vad;
    /*
     * 客户端请求重协商，实际会走 offer/answer 交换 SDP，值为 true 表示要重启ICE
     */
    protobuf_c_boolean negotiation;
  };
};
#define RTC__SIGNAL_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rtc__signal_request__descriptor) \
, 0, 0, RTC__SIGNAL_REQUEST__MESSAGE__NOT_SET, {0} }


typedef enum {
  RTC__SIGNAL_RESPONSE__MESSAGE__NOT_SET = 0,
  RTC__SIGNAL_RESPONSE__MESSAGE_OFFER = 2,
  RTC__SIGNAL_RESPONSE__MESSAGE_CANDIDATE = 3,
  RTC__SIGNAL_RESPONSE__MESSAGE_ADD_TRACK = 4,
  RTC__SIGNAL_RESPONSE__MESSAGE_REMOVE_TRACK = 5,
  RTC__SIGNAL_RESPONSE__MESSAGE_JOINED = 6,
  RTC__SIGNAL_RESPONSE__MESSAGE_LEAVED = 7,
  RTC__SIGNAL_RESPONSE__MESSAGE_STATE = 8,
  RTC__SIGNAL_RESPONSE__MESSAGE_ADDR = 9,
  RTC__SIGNAL_RESPONSE__MESSAGE_PONG = 10,
  RTC__SIGNAL_RESPONSE__MESSAGE_STATS = 11,
  RTC__SIGNAL_RESPONSE__MESSAGE_RESPONSE = 12,
  RTC__SIGNAL_RESPONSE__MESSAGE_VAD = 13,
  RTC__SIGNAL_RESPONSE__MESSAGE_BROADCAST = 14,
  RTC__SIGNAL_RESPONSE__MESSAGE_ANSWER = 15,
  RTC__SIGNAL_RESPONSE__MESSAGE_NEGOTIATION = 16,
  RTC__SIGNAL_RESPONSE__MESSAGE_SUBSCRIBE = 17,
  RTC__SIGNAL_RESPONSE__MESSAGE_CONFIG_DEPRECATED = 18,
  RTC__SIGNAL_RESPONSE__MESSAGE_NODE_LIST = 19,
  RTC__SIGNAL_RESPONSE__MESSAGE_STATES = 20,
  RTC__SIGNAL_RESPONSE__MESSAGE_CONFIG = 22,
  RTC__SIGNAL_RESPONSE__MESSAGE_TOKEN = 23
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(RTC__SIGNAL_RESPONSE__MESSAGE__CASE)
} Rtc__SignalResponse__MessageCase;

/*
 * 服务端给客户端的回应
 */
struct  Rtc__SignalResponse
{
  ProtobufCMessage base;
  /*
   * 客户端的请求消息 ID
   */
  uint32_t id;
  /*
   * 通道标识，对于 SFU+Mesh 模式，0=SFU通道，1=Mesh通道
   */
  uint32_t channel;
  Rtc__SignalResponse__MessageCase message_case;
  union {
    /*
     * 服务端告诉客户端其 IP 地址
     */
    char *addr;
    /*
     * 服务端的 ICE 候选信息（IP、端口等），值是 RTCIceCandidate JSON
     * 编码后的字符串
     */
    char *candidate;
    /*
     * deprecated. 旧 config 已废弃
     */
    char *config_deprecated;
    /*
     * 服务端返回的 RTP 统计信息
     */
    char *stats;
    /*
     * 刷新 token
     */
    char *token;
    /*
     * 服务端通知房间中所有人：某人发布 Track
     */
    Rtc__AddTrack *add_track;
    /*
     * Mesh 远端 answer
     */
    Rtc__SessionDescription *answer;
    /*
     * 服务端转发广播消息
     */
    Rtc__Broadcast *broadcast;
    /*
     * Mesh 下发 RTC 配置
     */
    Rtc__RtcConfig *config;
    /*
     * 服务端通知房间中所有人：某人加入房间
     */
    Rtc__Joined *joined;
    /*
     * 服务端通知房间中所有人：某个人离开了
     */
    Rtc__Leaved *leaved;
    /*
     * 节点信息列表
     */
    Rtc__NodeList *node_list;
    /*
     * 服务端先发 offer 给客户端，然后客户端回复 answer
     */
    Rtc__SessionDescription *offer;
    /*
     * 服务端返回的心跳包
     */
    Rtc__Pong *pong;
    /*
     * 服务端通知房间中所有人：某人取消发布 Track
     */
    Rtc__RemoveTrack *remove_track;
    /*
     * 服务端回应客户端的请求
     */
    Rtc__Response *response;
    /*
     * 媒体连接状态列表
     */
    Rtc__States *states;
    /*
     * Mesh 远端请求订阅/取消订阅音视频 Track
     */
    Rtc__Subscribe *subscribe;
    /*
     * 服务端主动发送房间中所有人的音量
     */
    Rtc__Vad *vad;
    /*
     * 服务端媒体通道连接状态
     */
    Rtc__PeerState state;
    /*
     * Mesh 远端请求重协商
     */
    protobuf_c_boolean negotiation;
  };
};
#define RTC__SIGNAL_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rtc__signal_response__descriptor) \
, 0, 0, RTC__SIGNAL_RESPONSE__MESSAGE__NOT_SET, {0} }


/*
 * PeerConnection 配置
 */
struct  Rtc__RtcConfig
{
  ProtobufCMessage base;
  /*
   * ICE 服务器列表
   */
  size_t n_ice_servers;
  Rtc__IceServer **ice_servers;
  /*
   * ICE 传输策略
   */
  Rtc__IcePolicy ice_policy;
};
#define RTC__RTC_CONFIG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rtc__rtc_config__descriptor) \
, 0,NULL, RTC__ICE_POLICY__ICE_POLICY_NONE }


/*
 * ICE 服务器信息
 */
struct  Rtc__IceServer
{
  ProtobufCMessage base;
  /*
   * URL 列表
   */
  size_t n_urls;
  char **urls;
  /*
   * 用户名，可选
   */
  char *username;
  /*
   * 凭证，可选
   */
  char *credential;
};
#define RTC__ICE_SERVER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rtc__ice_server__descriptor) \
, 0,NULL, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/*
 * SDP（媒体信息，例如编码、证书指纹等）
 */
struct  Rtc__SessionDescription
{
  ProtobufCMessage base;
  /*
   * SDP 类型，对应 RTCSessionDescriptionInit.type，需要将 RTCSdpType 转 SdpType
   */
  Rtc__SdpType type;
  /*
   * 对应 RTCSessionDescriptionInit.sdp
   */
  char *sdp;
};
#define RTC__SESSION_DESCRIPTION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rtc__session_description__descriptor) \
, RTC__SDP_TYPE__SDP_TYPE_UNKNOWN, (char *)protobuf_c_empty_string }


/*
 * 订阅/取消订阅全部或某个音频或视频 Track
 */
struct  Rtc__Subscribe__Media
{
  ProtobufCMessage base;
  /*
   * 是否订阅，true 表示订阅，false 表示取消订阅
   */
  protobuf_c_boolean subscribe;
  /*
   * Track ID 列表，空表示全部
   */
  size_t n_tracks;
  char **tracks;
};
#define RTC__SUBSCRIBE__MEDIA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rtc__subscribe__media__descriptor) \
, 0, 0,NULL }


struct  Rtc__Subscribe__Options
{
  ProtobufCMessage base;
  /*
   * 是否自动订阅音视频 Track
   */
  protobuf_c_boolean auto_subscribe;
};
#define RTC__SUBSCRIBE__OPTIONS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rtc__subscribe__options__descriptor) \
, 0 }


/*
 * 客户端请求订阅/取消订阅全部或某个音频或视频 Track
 */
struct  Rtc__Subscribe
{
  ProtobufCMessage base;
  /*
   * 订阅/取消订阅音频 Track
   */
  Rtc__Subscribe__Media *audio;
  /*
   * 订阅/取消订阅视频 Track
   */
  Rtc__Subscribe__Media *video;
  /*
   * 设置订阅参数
   */
  Rtc__Subscribe__Options *options;
};
#define RTC__SUBSCRIBE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rtc__subscribe__descriptor) \
, NULL, NULL, NULL }


/*
 * 告诉房间中的所有人：某人发布 Track
 */
struct  Rtc__AddTrack
{
  ProtobufCMessage base;
  /*
   * Track 信息列表
   */
  size_t n_tracks;
  Rtc__TrackInfo **tracks;
};
#define RTC__ADD_TRACK__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rtc__add_track__descriptor) \
, 0,NULL }


/*
 * Track 信息
 */
struct  Rtc__TrackInfo
{
  ProtobufCMessage base;
  /*
   * 发布者 ID
   */
  char *peer_id;
  /*
   * 流 ID
   */
  char *stream_id;
  /*
   * Track ID
   */
  char *id;
  /*
   * MIME 类型
   */
  char *mime_type;
  /*
   * SSRC 同步源标识符，在 Volume 中用到
   */
  uint32_t ssrc;
  /*
   * 编码特定参数
   */
  char *fmtp_line;
};
#define RTC__TRACK_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rtc__track_info__descriptor) \
, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string }


/*
 * 告诉房间中的所有人：取消发布 Track
 */
struct  Rtc__RemoveTrack
{
  ProtobufCMessage base;
  /*
   * Track ID 列表
   */
  size_t n_tracks;
  char **tracks;
};
#define RTC__REMOVE_TRACK__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rtc__remove_track__descriptor) \
, 0,NULL }


/*
 * 媒体连接状态
 */
struct  Rtc__State
{
  ProtobufCMessage base;
  /*
   * 媒体连接状态
   */
  Rtc__PeerState state;
  /*
   * Peer ID
   */
  char *peer_id;
};
#define RTC__STATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rtc__state__descriptor) \
, RTC__PEER_STATE__PEER_STATE_UNKNOWN, (char *)protobuf_c_empty_string }


/*
 * 媒体连接状态列表
 */
struct  Rtc__States
{
  ProtobufCMessage base;
  /*
   * 媒体连接状态列表
   */
  size_t n_states;
  Rtc__State **states;
};
#define RTC__STATES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rtc__states__descriptor) \
, 0,NULL }


/*
 * 客户端加入房间的参数
 */
struct  Rtc__Options
{
  ProtobufCMessage base;
  /*
   * 首选视频编码列表，例如：h265,h264,vp8
   */
  size_t n_codecs;
  char **codecs;
  /*
   * 是否自动订阅音视频 Track
   */
  protobuf_c_boolean auto_subscribe;
  /*
   * 发布多少个音频 Track，0 表示不发布
   */
  uint32_t publishing_audio;
  /*
   * 发布多少个视频 Track，0 表示不发布
   */
  uint32_t publishing_video;
  /*
   * 是否重新创建媒体连接
   */
  protobuf_c_boolean recreating;
  /*
   * 首先节点可用区，可选，例如：cn-shanghai, us-east, eu-frankfurt
   */
  char *zone;
  /*
   * 首选节点地区，可选，例如：cn, us, eu
   */
  char *region;
  /*
   * 首选节点位置，可选，可填入客户端经纬度
   */
  Rtc__Location *location;
  /*
   * 首选节点 IP，可选，根据 IP 选择节点
   */
  char *ip;
  /*
   * 客户端是否为 Offer 端
   */
  protobuf_c_boolean offerer;
  /*
   * ICE 传输策略
   */
  Rtc__IcePolicy ice_policy;
  /*
   * 是否协调视频的方向（Coordination of Video Orientation, CVO）
   */
  protobuf_c_boolean video_orientation;
};
#define RTC__OPTIONS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rtc__options__descriptor) \
, 0,NULL, 0, 0, 0, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, NULL, (char *)protobuf_c_empty_string, 0, RTC__ICE_POLICY__ICE_POLICY_NONE, 0 }


/*
 * 地理位置
 */
struct  Rtc__Location
{
  ProtobufCMessage base;
  /*
   * 纬度
   */
  float latitude;
  /*
   * 经度
   */
  float longitude;
};
#define RTC__LOCATION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rtc__location__descriptor) \
, 0, 0 }


/*
 * 客户端加入了房间
 */
struct  Rtc__Joined
{
  ProtobufCMessage base;
  /*
   * 房间中的 Peer 列表
   */
  size_t n_peers;
  Rtc__PeerInfo **peers;
  /*
   * deprecated. 旧 config 已废弃
   */
  char *config_deprecated;
  /*
   * RTC 配置
   */
  Rtc__RtcConfig *config;
};
#define RTC__JOINED__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rtc__joined__descriptor) \
, 0,NULL, (char *)protobuf_c_empty_string, NULL }


/*
 * 客户端离开了房间
 */
struct  Rtc__Leaved
{
  ProtobufCMessage base;
  /*
   * 离开者 ID
   */
  char *peer_id;
  /*
   * 关闭原因
   */
  Rtc__CloseReason reason;
};
#define RTC__LEAVED__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rtc__leaved__descriptor) \
, (char *)protobuf_c_empty_string, RTC__CLOSE_REASON__REASON_USER_LEAVE }


/*
 * 客户端主动离开房间，自己离开不用填写 peer_id
 */
struct  Rtc__Leave
{
  ProtobufCMessage base;
  /*
   * 离开者 ID
   */
  char *peer_id;
};
#define RTC__LEAVE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rtc__leave__descriptor) \
, (char *)protobuf_c_empty_string }


/*
 * 客户端发送 Ping，服务端返回 Pong
 */
struct  Rtc__Ping
{
  ProtobufCMessage base;
  /*
   * 客户端的当前时间戳，单位毫秒，只取低 32 位
   */
  uint32_t timestamp;
  /*
   * 往返回时间，单位毫秒。由客户端计算：将当前时间毫秒数取低 32 位，然后减去
   * Pong 中的 timestamp
   */
  uint32_t rtt;
};
#define RTC__PING__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rtc__ping__descriptor) \
, 0, 0 }


/*
 * 服务端收到客户端发送 Ping 之后，返回 Pong
 */
struct  Rtc__Pong
{
  ProtobufCMessage base;
  /*
   * 客户端 Ping 中 timestamp
   */
  uint32_t timestamp;
};
#define RTC__PONG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rtc__pong__descriptor) \
, 0 }


/*
 * 服务端收到客户端的请求后，处理结事将会返回结果
 */
struct  Rtc__Response
{
  ProtobufCMessage base;
  /*
   * 状态码，200 为成功，其他为失败
   */
  uint32_t code;
  /*
   * 如果成功，返回 “ok”，否则返回错误描述信息
   */
  char *text;
};
#define RTC__RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rtc__response__descriptor) \
, 0, (char *)protobuf_c_empty_string }


/*
 * 服务端主动发送房间所有的音量，通过 DataChannel 发送
 */
struct  Rtc__Vad
{
  ProtobufCMessage base;
  /*
   * 音量列表
   */
  size_t n_volumes;
  Rtc__Volume **volumes;
};
#define RTC__VAD__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rtc__vad__descriptor) \
, 0,NULL }


/*
 * 音量信息
 */
struct  Rtc__Volume
{
  ProtobufCMessage base;
  /*
   * SSRC 同步源标识符，对应 TrackInfo 中的 ssrc
   */
  uint32_t ssrc;
  /*
   * 音量值，0-100
   */
  int32_t volume;
};
#define RTC__VOLUME__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rtc__volume__descriptor) \
, 0, 0 }


typedef enum {
  RTC__BROADCAST__MESSAGE__NOT_SET = 0,
  RTC__BROADCAST__MESSAGE_DATA = 3,
  RTC__BROADCAST__MESSAGE_MUTE = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(RTC__BROADCAST__MESSAGE__CASE)
} Rtc__Broadcast__MessageCase;

/*
 * 向房间广播消息，通过 DataChannel 发送
 */
struct  Rtc__Broadcast
{
  ProtobufCMessage base;
  /*
   * 发送者 Peer ID，由服务端填写，客户端不填写
   */
  char *from;
  /*
   * 包含的接收者 Peer ID，可选，空值表示广播给所有人
   */
  size_t n_include;
  char **include;
  /*
   * 排除的接收者 Peer ID，可选
   */
  size_t n_exclude;
  char **exclude;
  Rtc__Broadcast__MessageCase message_case;
  union {
    /*
     * 任意数据
     */
    ProtobufCBinaryData data;
    /*
     * 静音/空帧状态
     */
    Rtc__Mute *mute;
  };
};
#define RTC__BROADCAST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rtc__broadcast__descriptor) \
, (char *)protobuf_c_empty_string, 0,NULL, 0,NULL, RTC__BROADCAST__MESSAGE__NOT_SET, { {0} } }


struct  Rtc__Mute__Media
{
  ProtobufCMessage base;
  /*
   * 是否静音/空帧，true 表示静音/空帧，false 表示取消静音/空帧
   */
  protobuf_c_boolean mute;
  /*
   * 时间戳，对应 RTP 包的 timestamp
   */
  uint32_t timestamp;
};
#define RTC__MUTE__MEDIA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rtc__mute__media__descriptor) \
, 0, 0 }


/*
 * 静音/空帧状态
 */
struct  Rtc__Mute
{
  ProtobufCMessage base;
  /*
   * 音频静音
   */
  Rtc__Mute__Media *audio;
  /*
   * 视频空帧
   */
  Rtc__Mute__Media *video;
};
#define RTC__MUTE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rtc__mute__descriptor) \
, NULL, NULL }


/*
 * Peer 信息
 */
struct  Rtc__PeerInfo
{
  ProtobufCMessage base;
  /*
   * Peer ID
   */
  char *id;
  /*
   * 房间 ID
   */
  char *room_id;
  /*
   * 应用 ID
   */
  char *app_id;
  /*
   * 业务节点（信令节点）ID
   */
  char *biz_node;
  /*
   * 媒体节点 ID
   */
  char *media_node;
  /*
   * 视频编码能力，例如：h265,h264,vp8
   */
  size_t n_codecs;
  char **codecs;
  /*
   * 节点 RTT 列表
   */
  size_t n_node_rtts;
  Rtc__NodeRtt **node_rtts;
  /*
   * 静音/空帧状态
   */
  Rtc__Mute *mute;
  /*
   * 客户端信令连接地址（IP:PORT）
   */
  char *addr;
  /*
   * 是否协调视频方向（Coordination of Video Orientation, CVO）
   */
  protobuf_c_boolean video_orientation;
  /*
   * 选择的通道
   */
  Rtc__SelectChannel *channel;
  /*
   * 客户端 SDK 版本号
   */
  uint32_t sdk_version;
  /*
   * 客户端操作系统类型
   */
  Rtc__OsType os_type;
  /*
   * 客户端操作系统版本号
   */
  uint32_t os_version;
};
#define RTC__PEER_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rtc__peer_info__descriptor) \
, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0,NULL, 0,NULL, NULL, (char *)protobuf_c_empty_string, 0, NULL, 0, RTC__OS_TYPE__OS_TYPE_UNKNOWN, 0 }


/*
 * SRTP Key
 */
struct  Rtc__SrtpKey
{
  ProtobufCMessage base;
  /*
   * 加密算法
   */
  Rtc__SrtpProfile profile;
  /*
   * 密钥
   */
  ProtobufCBinaryData key;
};
#define RTC__SRTP_KEY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rtc__srtp_key__descriptor) \
, RTC__SRTP_PROFILE__UNKNOWN, {0,NULL} }


/*
 * 节点列表
 */
struct  Rtc__NodeList
{
  ProtobufCMessage base;
  /*
   * 节点 IP 列表
   */
  size_t n_ips;
  char **ips;
  /*
   * STUN 服务端口
   */
  uint32_t stun_port;
  /*
   * 客户端 IP
   */
  char *client_ip;
};
#define RTC__NODE_LIST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rtc__node_list__descriptor) \
, 0,NULL, 0, (char *)protobuf_c_empty_string }


/*
 * 节点 RTT 列表
 */
struct  Rtc__NodeRtts
{
  ProtobufCMessage base;
  /*
   * 节点 RTT 列表
   */
  size_t n_node_rtts;
  Rtc__NodeRtt **node_rtts;
};
#define RTC__NODE_RTTS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rtc__node_rtts__descriptor) \
, 0,NULL }


/*
 * 节点 RTT
 */
struct  Rtc__NodeRtt
{
  ProtobufCMessage base;
  /*
   * 节点 IP
   */
  char *ip;
  /*
   * RTT，单位毫秒
   */
  uint32_t rtt;
};
#define RTC__NODE_RTT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rtc__node_rtt__descriptor) \
, (char *)protobuf_c_empty_string, 0 }


/*
 * 选择通道
 */
struct  Rtc__SelectChannel
{
  ProtobufCMessage base;
  Rtc__Channel channel;
};
#define RTC__SELECT_CHANNEL__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rtc__select_channel__descriptor) \
, RTC__CHANNEL__CHANNEL_SFU }


/*
 * 通话统计信息
 */
struct  Rtc__Stats
{
  ProtobufCMessage base;
  /*
   * 记录唯一标识 ID，由服务端填写
   */
  int64_t id;
  /*
   * 用户 ID，可由服务端填写
   */
  char *peer_id;
  /*
   * 房间 ID (会话 ID)，可由服务端填写
   */
  char *room_id;
  /*
   * 应用 ID，可由服务端填写
   */
  char *app_id;
  /*
   * 统计信息来源，由服务端填写
   */
  Rtc__Source source;
  /*
   * 媒体/数据类型
   */
  Rtc__DataType data_type;
  /*
   * 传输方向
   */
  Rtc__Direction direction;
  /*
   * 媒体开始时间，单位：毫秒，Unix Time（1970-01-01 UTC 起的毫秒数）
   * 可由服务端填写，根据当前时间减去通话时长计算得到
   */
  int64_t start_time;
  /*
   * 媒体结束时间，单位：毫秒，Unix Time（1970-01-01 UTC 起的毫秒数）
   * 可由服务端填写，根据当前时间加上通话时长计算得到
   */
  int64_t end_time;
  /*
   * 通话时长，单位：毫秒
   */
  int64_t duration;
  /*
   * 信令节点 ID，可由服务端填写
   */
  char *signal_node_id;
  /*
   * 客户端信令 IP，可由服务端填写
   */
  char *signal_ip;
  /*
   * 客户端信令端口，可由服务端填写
   */
  uint32_t signal_port;
  /*
   * 平均信令通道往返时间 (Signaling RTT)，单位：毫秒，可由服务端填写
   */
  uint32_t signal_rtt;
  /*
   * 媒体传输协议 (如 UDP/TCP)
   */
  Rtc__Protocol media_protocol;
  /*
   * 媒体节点 ID，可由服务端填写
   */
  char *media_node_id;
  /*
   * 远端媒体 IP
   */
  char *media_remote_ip;
  /*
   * 远端媒体端口
   */
  uint32_t media_remote_port;
  /*
   * 客户端媒体 IP
   */
  char *media_ip;
  /*
   * 客户端媒体端口
   */
  uint32_t media_port;
  /*
   * 平均媒体通道往返时间 (Media RTT)，单位：毫秒
   */
  uint32_t media_rtt;
  /*
   * 媒体轨道 ID，填写原始 Track ID（发布者 Track ID）
   */
  char *track_id;
  /*
   * 媒体同步源标识符 (Synchronization Source Identifier)
   */
  uint32_t ssrc;
  /*
   * 发送的字节总数
   */
  uint64_t bytes_sent;
  /*
   * 接收的字节总数
   */
  uint64_t bytes_received;
  /*
   * 发送的 RTP 包头部字节总数
   */
  uint64_t header_bytes_sent;
  /*
   * 接收的 RTP 包头部字节总数
   */
  uint64_t header_bytes_received;
  /*
   * 发送的数据包总数
   */
  uint64_t packets_sent;
  /*
   * 接收的数据包总数
   */
  uint64_t packets_received;
  /*
   * 丢包总数，表示最终判定为彻底丢失的包
   */
  int64_t packets_lost;
  /*
   * 丢包率，万分比，例如：5000 表示 50%
   */
  int32_t packet_loss_rate;
  /*
   * 否定应答次数 (Negative Acknowledgment Count)，即重传请求次数
   */
  uint32_t nack_count;
  /*
   * 平均网络抖动，单位：毫秒
   */
  uint32_t jitter;
  /*
   * 平均往返时间 (Round Trip Time)，单位：毫秒
   */
  uint32_t round_trip_time;
  /*
   * 视频卡顿次数
   */
  uint32_t freeze_count;
  /*
   * 视频卡顿总时长，单位：毫秒
   */
  uint32_t total_freezes_duration;
  /*
   * 视频卡顿率，万分比，例如：5000 表示 50%
   */
  uint32_t freeze_rate;
  /*
   * 视频全帧请求次数 (Full Intra Request Count)，即请求 I 帧（独立的完整图像）次数
   */
  uint32_t fir_count;
  /*
   * 视频图像丢失指示次数(Picture Loss Indication Count)，即关键帧请求次数
   */
  uint32_t pli_count;
  /*
   * 视频发送总帧数
   */
  uint32_t frames_sent;
  /*
   * 视频接收总帧数
   */
  uint32_t frames_received;
  /*
   * 视频平均帧率，单位：帧每秒
   */
  uint32_t frames_per_second;
  /*
   * 视频帧分辨率宽度
   */
  uint32_t frame_width;
  /*
   * 视频帧分辨率高度
   */
  uint32_t frame_height;
};
#define RTC__STATS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rtc__stats__descriptor) \
, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, RTC__SOURCE__SOURCE_SERVER, RTC__DATA_TYPE__DATA_TYPE_UNKNOWN, RTC__DIRECTION__DIRECTION_UNKNOWN, 0, 0, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, 0, RTC__PROTOCOL__PROTOCOL_UNKNOWN, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string, 0, 0, (char *)protobuf_c_empty_string, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }


/* Rtc__SignalRequest methods */
void   rtc__signal_request__init
                     (Rtc__SignalRequest         *message);
size_t rtc__signal_request__get_packed_size
                     (const Rtc__SignalRequest   *message);
size_t rtc__signal_request__pack
                     (const Rtc__SignalRequest   *message,
                      uint8_t             *out);
size_t rtc__signal_request__pack_to_buffer
                     (const Rtc__SignalRequest   *message,
                      ProtobufCBuffer     *buffer);
Rtc__SignalRequest *
       rtc__signal_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rtc__signal_request__free_unpacked
                     (Rtc__SignalRequest *message,
                      ProtobufCAllocator *allocator);
/* Rtc__SignalResponse methods */
void   rtc__signal_response__init
                     (Rtc__SignalResponse         *message);
size_t rtc__signal_response__get_packed_size
                     (const Rtc__SignalResponse   *message);
size_t rtc__signal_response__pack
                     (const Rtc__SignalResponse   *message,
                      uint8_t             *out);
size_t rtc__signal_response__pack_to_buffer
                     (const Rtc__SignalResponse   *message,
                      ProtobufCBuffer     *buffer);
Rtc__SignalResponse *
       rtc__signal_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rtc__signal_response__free_unpacked
                     (Rtc__SignalResponse *message,
                      ProtobufCAllocator *allocator);
/* Rtc__RtcConfig methods */
void   rtc__rtc_config__init
                     (Rtc__RtcConfig         *message);
size_t rtc__rtc_config__get_packed_size
                     (const Rtc__RtcConfig   *message);
size_t rtc__rtc_config__pack
                     (const Rtc__RtcConfig   *message,
                      uint8_t             *out);
size_t rtc__rtc_config__pack_to_buffer
                     (const Rtc__RtcConfig   *message,
                      ProtobufCBuffer     *buffer);
Rtc__RtcConfig *
       rtc__rtc_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rtc__rtc_config__free_unpacked
                     (Rtc__RtcConfig *message,
                      ProtobufCAllocator *allocator);
/* Rtc__IceServer methods */
void   rtc__ice_server__init
                     (Rtc__IceServer         *message);
size_t rtc__ice_server__get_packed_size
                     (const Rtc__IceServer   *message);
size_t rtc__ice_server__pack
                     (const Rtc__IceServer   *message,
                      uint8_t             *out);
size_t rtc__ice_server__pack_to_buffer
                     (const Rtc__IceServer   *message,
                      ProtobufCBuffer     *buffer);
Rtc__IceServer *
       rtc__ice_server__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rtc__ice_server__free_unpacked
                     (Rtc__IceServer *message,
                      ProtobufCAllocator *allocator);
/* Rtc__SessionDescription methods */
void   rtc__session_description__init
                     (Rtc__SessionDescription         *message);
size_t rtc__session_description__get_packed_size
                     (const Rtc__SessionDescription   *message);
size_t rtc__session_description__pack
                     (const Rtc__SessionDescription   *message,
                      uint8_t             *out);
size_t rtc__session_description__pack_to_buffer
                     (const Rtc__SessionDescription   *message,
                      ProtobufCBuffer     *buffer);
Rtc__SessionDescription *
       rtc__session_description__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rtc__session_description__free_unpacked
                     (Rtc__SessionDescription *message,
                      ProtobufCAllocator *allocator);
/* Rtc__Subscribe__Media methods */
void   rtc__subscribe__media__init
                     (Rtc__Subscribe__Media         *message);
/* Rtc__Subscribe__Options methods */
void   rtc__subscribe__options__init
                     (Rtc__Subscribe__Options         *message);
/* Rtc__Subscribe methods */
void   rtc__subscribe__init
                     (Rtc__Subscribe         *message);
size_t rtc__subscribe__get_packed_size
                     (const Rtc__Subscribe   *message);
size_t rtc__subscribe__pack
                     (const Rtc__Subscribe   *message,
                      uint8_t             *out);
size_t rtc__subscribe__pack_to_buffer
                     (const Rtc__Subscribe   *message,
                      ProtobufCBuffer     *buffer);
Rtc__Subscribe *
       rtc__subscribe__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rtc__subscribe__free_unpacked
                     (Rtc__Subscribe *message,
                      ProtobufCAllocator *allocator);
/* Rtc__AddTrack methods */
void   rtc__add_track__init
                     (Rtc__AddTrack         *message);
size_t rtc__add_track__get_packed_size
                     (const Rtc__AddTrack   *message);
size_t rtc__add_track__pack
                     (const Rtc__AddTrack   *message,
                      uint8_t             *out);
size_t rtc__add_track__pack_to_buffer
                     (const Rtc__AddTrack   *message,
                      ProtobufCBuffer     *buffer);
Rtc__AddTrack *
       rtc__add_track__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rtc__add_track__free_unpacked
                     (Rtc__AddTrack *message,
                      ProtobufCAllocator *allocator);
/* Rtc__TrackInfo methods */
void   rtc__track_info__init
                     (Rtc__TrackInfo         *message);
size_t rtc__track_info__get_packed_size
                     (const Rtc__TrackInfo   *message);
size_t rtc__track_info__pack
                     (const Rtc__TrackInfo   *message,
                      uint8_t             *out);
size_t rtc__track_info__pack_to_buffer
                     (const Rtc__TrackInfo   *message,
                      ProtobufCBuffer     *buffer);
Rtc__TrackInfo *
       rtc__track_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rtc__track_info__free_unpacked
                     (Rtc__TrackInfo *message,
                      ProtobufCAllocator *allocator);
/* Rtc__RemoveTrack methods */
void   rtc__remove_track__init
                     (Rtc__RemoveTrack         *message);
size_t rtc__remove_track__get_packed_size
                     (const Rtc__RemoveTrack   *message);
size_t rtc__remove_track__pack
                     (const Rtc__RemoveTrack   *message,
                      uint8_t             *out);
size_t rtc__remove_track__pack_to_buffer
                     (const Rtc__RemoveTrack   *message,
                      ProtobufCBuffer     *buffer);
Rtc__RemoveTrack *
       rtc__remove_track__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rtc__remove_track__free_unpacked
                     (Rtc__RemoveTrack *message,
                      ProtobufCAllocator *allocator);
/* Rtc__State methods */
void   rtc__state__init
                     (Rtc__State         *message);
size_t rtc__state__get_packed_size
                     (const Rtc__State   *message);
size_t rtc__state__pack
                     (const Rtc__State   *message,
                      uint8_t             *out);
size_t rtc__state__pack_to_buffer
                     (const Rtc__State   *message,
                      ProtobufCBuffer     *buffer);
Rtc__State *
       rtc__state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rtc__state__free_unpacked
                     (Rtc__State *message,
                      ProtobufCAllocator *allocator);
/* Rtc__States methods */
void   rtc__states__init
                     (Rtc__States         *message);
size_t rtc__states__get_packed_size
                     (const Rtc__States   *message);
size_t rtc__states__pack
                     (const Rtc__States   *message,
                      uint8_t             *out);
size_t rtc__states__pack_to_buffer
                     (const Rtc__States   *message,
                      ProtobufCBuffer     *buffer);
Rtc__States *
       rtc__states__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rtc__states__free_unpacked
                     (Rtc__States *message,
                      ProtobufCAllocator *allocator);
/* Rtc__Options methods */
void   rtc__options__init
                     (Rtc__Options         *message);
size_t rtc__options__get_packed_size
                     (const Rtc__Options   *message);
size_t rtc__options__pack
                     (const Rtc__Options   *message,
                      uint8_t             *out);
size_t rtc__options__pack_to_buffer
                     (const Rtc__Options   *message,
                      ProtobufCBuffer     *buffer);
Rtc__Options *
       rtc__options__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rtc__options__free_unpacked
                     (Rtc__Options *message,
                      ProtobufCAllocator *allocator);
/* Rtc__Location methods */
void   rtc__location__init
                     (Rtc__Location         *message);
size_t rtc__location__get_packed_size
                     (const Rtc__Location   *message);
size_t rtc__location__pack
                     (const Rtc__Location   *message,
                      uint8_t             *out);
size_t rtc__location__pack_to_buffer
                     (const Rtc__Location   *message,
                      ProtobufCBuffer     *buffer);
Rtc__Location *
       rtc__location__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rtc__location__free_unpacked
                     (Rtc__Location *message,
                      ProtobufCAllocator *allocator);
/* Rtc__Joined methods */
void   rtc__joined__init
                     (Rtc__Joined         *message);
size_t rtc__joined__get_packed_size
                     (const Rtc__Joined   *message);
size_t rtc__joined__pack
                     (const Rtc__Joined   *message,
                      uint8_t             *out);
size_t rtc__joined__pack_to_buffer
                     (const Rtc__Joined   *message,
                      ProtobufCBuffer     *buffer);
Rtc__Joined *
       rtc__joined__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rtc__joined__free_unpacked
                     (Rtc__Joined *message,
                      ProtobufCAllocator *allocator);
/* Rtc__Leaved methods */
void   rtc__leaved__init
                     (Rtc__Leaved         *message);
size_t rtc__leaved__get_packed_size
                     (const Rtc__Leaved   *message);
size_t rtc__leaved__pack
                     (const Rtc__Leaved   *message,
                      uint8_t             *out);
size_t rtc__leaved__pack_to_buffer
                     (const Rtc__Leaved   *message,
                      ProtobufCBuffer     *buffer);
Rtc__Leaved *
       rtc__leaved__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rtc__leaved__free_unpacked
                     (Rtc__Leaved *message,
                      ProtobufCAllocator *allocator);
/* Rtc__Leave methods */
void   rtc__leave__init
                     (Rtc__Leave         *message);
size_t rtc__leave__get_packed_size
                     (const Rtc__Leave   *message);
size_t rtc__leave__pack
                     (const Rtc__Leave   *message,
                      uint8_t             *out);
size_t rtc__leave__pack_to_buffer
                     (const Rtc__Leave   *message,
                      ProtobufCBuffer     *buffer);
Rtc__Leave *
       rtc__leave__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rtc__leave__free_unpacked
                     (Rtc__Leave *message,
                      ProtobufCAllocator *allocator);
/* Rtc__Ping methods */
void   rtc__ping__init
                     (Rtc__Ping         *message);
size_t rtc__ping__get_packed_size
                     (const Rtc__Ping   *message);
size_t rtc__ping__pack
                     (const Rtc__Ping   *message,
                      uint8_t             *out);
size_t rtc__ping__pack_to_buffer
                     (const Rtc__Ping   *message,
                      ProtobufCBuffer     *buffer);
Rtc__Ping *
       rtc__ping__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rtc__ping__free_unpacked
                     (Rtc__Ping *message,
                      ProtobufCAllocator *allocator);
/* Rtc__Pong methods */
void   rtc__pong__init
                     (Rtc__Pong         *message);
size_t rtc__pong__get_packed_size
                     (const Rtc__Pong   *message);
size_t rtc__pong__pack
                     (const Rtc__Pong   *message,
                      uint8_t             *out);
size_t rtc__pong__pack_to_buffer
                     (const Rtc__Pong   *message,
                      ProtobufCBuffer     *buffer);
Rtc__Pong *
       rtc__pong__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rtc__pong__free_unpacked
                     (Rtc__Pong *message,
                      ProtobufCAllocator *allocator);
/* Rtc__Response methods */
void   rtc__response__init
                     (Rtc__Response         *message);
size_t rtc__response__get_packed_size
                     (const Rtc__Response   *message);
size_t rtc__response__pack
                     (const Rtc__Response   *message,
                      uint8_t             *out);
size_t rtc__response__pack_to_buffer
                     (const Rtc__Response   *message,
                      ProtobufCBuffer     *buffer);
Rtc__Response *
       rtc__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rtc__response__free_unpacked
                     (Rtc__Response *message,
                      ProtobufCAllocator *allocator);
/* Rtc__Vad methods */
void   rtc__vad__init
                     (Rtc__Vad         *message);
size_t rtc__vad__get_packed_size
                     (const Rtc__Vad   *message);
size_t rtc__vad__pack
                     (const Rtc__Vad   *message,
                      uint8_t             *out);
size_t rtc__vad__pack_to_buffer
                     (const Rtc__Vad   *message,
                      ProtobufCBuffer     *buffer);
Rtc__Vad *
       rtc__vad__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rtc__vad__free_unpacked
                     (Rtc__Vad *message,
                      ProtobufCAllocator *allocator);
/* Rtc__Volume methods */
void   rtc__volume__init
                     (Rtc__Volume         *message);
size_t rtc__volume__get_packed_size
                     (const Rtc__Volume   *message);
size_t rtc__volume__pack
                     (const Rtc__Volume   *message,
                      uint8_t             *out);
size_t rtc__volume__pack_to_buffer
                     (const Rtc__Volume   *message,
                      ProtobufCBuffer     *buffer);
Rtc__Volume *
       rtc__volume__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rtc__volume__free_unpacked
                     (Rtc__Volume *message,
                      ProtobufCAllocator *allocator);
/* Rtc__Broadcast methods */
void   rtc__broadcast__init
                     (Rtc__Broadcast         *message);
size_t rtc__broadcast__get_packed_size
                     (const Rtc__Broadcast   *message);
size_t rtc__broadcast__pack
                     (const Rtc__Broadcast   *message,
                      uint8_t             *out);
size_t rtc__broadcast__pack_to_buffer
                     (const Rtc__Broadcast   *message,
                      ProtobufCBuffer     *buffer);
Rtc__Broadcast *
       rtc__broadcast__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rtc__broadcast__free_unpacked
                     (Rtc__Broadcast *message,
                      ProtobufCAllocator *allocator);
/* Rtc__Mute__Media methods */
void   rtc__mute__media__init
                     (Rtc__Mute__Media         *message);
/* Rtc__Mute methods */
void   rtc__mute__init
                     (Rtc__Mute         *message);
size_t rtc__mute__get_packed_size
                     (const Rtc__Mute   *message);
size_t rtc__mute__pack
                     (const Rtc__Mute   *message,
                      uint8_t             *out);
size_t rtc__mute__pack_to_buffer
                     (const Rtc__Mute   *message,
                      ProtobufCBuffer     *buffer);
Rtc__Mute *
       rtc__mute__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rtc__mute__free_unpacked
                     (Rtc__Mute *message,
                      ProtobufCAllocator *allocator);
/* Rtc__PeerInfo methods */
void   rtc__peer_info__init
                     (Rtc__PeerInfo         *message);
size_t rtc__peer_info__get_packed_size
                     (const Rtc__PeerInfo   *message);
size_t rtc__peer_info__pack
                     (const Rtc__PeerInfo   *message,
                      uint8_t             *out);
size_t rtc__peer_info__pack_to_buffer
                     (const Rtc__PeerInfo   *message,
                      ProtobufCBuffer     *buffer);
Rtc__PeerInfo *
       rtc__peer_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rtc__peer_info__free_unpacked
                     (Rtc__PeerInfo *message,
                      ProtobufCAllocator *allocator);
/* Rtc__SrtpKey methods */
void   rtc__srtp_key__init
                     (Rtc__SrtpKey         *message);
size_t rtc__srtp_key__get_packed_size
                     (const Rtc__SrtpKey   *message);
size_t rtc__srtp_key__pack
                     (const Rtc__SrtpKey   *message,
                      uint8_t             *out);
size_t rtc__srtp_key__pack_to_buffer
                     (const Rtc__SrtpKey   *message,
                      ProtobufCBuffer     *buffer);
Rtc__SrtpKey *
       rtc__srtp_key__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rtc__srtp_key__free_unpacked
                     (Rtc__SrtpKey *message,
                      ProtobufCAllocator *allocator);
/* Rtc__NodeList methods */
void   rtc__node_list__init
                     (Rtc__NodeList         *message);
size_t rtc__node_list__get_packed_size
                     (const Rtc__NodeList   *message);
size_t rtc__node_list__pack
                     (const Rtc__NodeList   *message,
                      uint8_t             *out);
size_t rtc__node_list__pack_to_buffer
                     (const Rtc__NodeList   *message,
                      ProtobufCBuffer     *buffer);
Rtc__NodeList *
       rtc__node_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rtc__node_list__free_unpacked
                     (Rtc__NodeList *message,
                      ProtobufCAllocator *allocator);
/* Rtc__NodeRtts methods */
void   rtc__node_rtts__init
                     (Rtc__NodeRtts         *message);
size_t rtc__node_rtts__get_packed_size
                     (const Rtc__NodeRtts   *message);
size_t rtc__node_rtts__pack
                     (const Rtc__NodeRtts   *message,
                      uint8_t             *out);
size_t rtc__node_rtts__pack_to_buffer
                     (const Rtc__NodeRtts   *message,
                      ProtobufCBuffer     *buffer);
Rtc__NodeRtts *
       rtc__node_rtts__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rtc__node_rtts__free_unpacked
                     (Rtc__NodeRtts *message,
                      ProtobufCAllocator *allocator);
/* Rtc__NodeRtt methods */
void   rtc__node_rtt__init
                     (Rtc__NodeRtt         *message);
size_t rtc__node_rtt__get_packed_size
                     (const Rtc__NodeRtt   *message);
size_t rtc__node_rtt__pack
                     (const Rtc__NodeRtt   *message,
                      uint8_t             *out);
size_t rtc__node_rtt__pack_to_buffer
                     (const Rtc__NodeRtt   *message,
                      ProtobufCBuffer     *buffer);
Rtc__NodeRtt *
       rtc__node_rtt__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rtc__node_rtt__free_unpacked
                     (Rtc__NodeRtt *message,
                      ProtobufCAllocator *allocator);
/* Rtc__SelectChannel methods */
void   rtc__select_channel__init
                     (Rtc__SelectChannel         *message);
size_t rtc__select_channel__get_packed_size
                     (const Rtc__SelectChannel   *message);
size_t rtc__select_channel__pack
                     (const Rtc__SelectChannel   *message,
                      uint8_t             *out);
size_t rtc__select_channel__pack_to_buffer
                     (const Rtc__SelectChannel   *message,
                      ProtobufCBuffer     *buffer);
Rtc__SelectChannel *
       rtc__select_channel__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rtc__select_channel__free_unpacked
                     (Rtc__SelectChannel *message,
                      ProtobufCAllocator *allocator);
/* Rtc__Stats methods */
void   rtc__stats__init
                     (Rtc__Stats         *message);
size_t rtc__stats__get_packed_size
                     (const Rtc__Stats   *message);
size_t rtc__stats__pack
                     (const Rtc__Stats   *message,
                      uint8_t             *out);
size_t rtc__stats__pack_to_buffer
                     (const Rtc__Stats   *message,
                      ProtobufCBuffer     *buffer);
Rtc__Stats *
       rtc__stats__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rtc__stats__free_unpacked
                     (Rtc__Stats *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Rtc__SignalRequest_Closure)
                 (const Rtc__SignalRequest *message,
                  void *closure_data);
typedef void (*Rtc__SignalResponse_Closure)
                 (const Rtc__SignalResponse *message,
                  void *closure_data);
typedef void (*Rtc__RtcConfig_Closure)
                 (const Rtc__RtcConfig *message,
                  void *closure_data);
typedef void (*Rtc__IceServer_Closure)
                 (const Rtc__IceServer *message,
                  void *closure_data);
typedef void (*Rtc__SessionDescription_Closure)
                 (const Rtc__SessionDescription *message,
                  void *closure_data);
typedef void (*Rtc__Subscribe__Media_Closure)
                 (const Rtc__Subscribe__Media *message,
                  void *closure_data);
typedef void (*Rtc__Subscribe__Options_Closure)
                 (const Rtc__Subscribe__Options *message,
                  void *closure_data);
typedef void (*Rtc__Subscribe_Closure)
                 (const Rtc__Subscribe *message,
                  void *closure_data);
typedef void (*Rtc__AddTrack_Closure)
                 (const Rtc__AddTrack *message,
                  void *closure_data);
typedef void (*Rtc__TrackInfo_Closure)
                 (const Rtc__TrackInfo *message,
                  void *closure_data);
typedef void (*Rtc__RemoveTrack_Closure)
                 (const Rtc__RemoveTrack *message,
                  void *closure_data);
typedef void (*Rtc__State_Closure)
                 (const Rtc__State *message,
                  void *closure_data);
typedef void (*Rtc__States_Closure)
                 (const Rtc__States *message,
                  void *closure_data);
typedef void (*Rtc__Options_Closure)
                 (const Rtc__Options *message,
                  void *closure_data);
typedef void (*Rtc__Location_Closure)
                 (const Rtc__Location *message,
                  void *closure_data);
typedef void (*Rtc__Joined_Closure)
                 (const Rtc__Joined *message,
                  void *closure_data);
typedef void (*Rtc__Leaved_Closure)
                 (const Rtc__Leaved *message,
                  void *closure_data);
typedef void (*Rtc__Leave_Closure)
                 (const Rtc__Leave *message,
                  void *closure_data);
typedef void (*Rtc__Ping_Closure)
                 (const Rtc__Ping *message,
                  void *closure_data);
typedef void (*Rtc__Pong_Closure)
                 (const Rtc__Pong *message,
                  void *closure_data);
typedef void (*Rtc__Response_Closure)
                 (const Rtc__Response *message,
                  void *closure_data);
typedef void (*Rtc__Vad_Closure)
                 (const Rtc__Vad *message,
                  void *closure_data);
typedef void (*Rtc__Volume_Closure)
                 (const Rtc__Volume *message,
                  void *closure_data);
typedef void (*Rtc__Broadcast_Closure)
                 (const Rtc__Broadcast *message,
                  void *closure_data);
typedef void (*Rtc__Mute__Media_Closure)
                 (const Rtc__Mute__Media *message,
                  void *closure_data);
typedef void (*Rtc__Mute_Closure)
                 (const Rtc__Mute *message,
                  void *closure_data);
typedef void (*Rtc__PeerInfo_Closure)
                 (const Rtc__PeerInfo *message,
                  void *closure_data);
typedef void (*Rtc__SrtpKey_Closure)
                 (const Rtc__SrtpKey *message,
                  void *closure_data);
typedef void (*Rtc__NodeList_Closure)
                 (const Rtc__NodeList *message,
                  void *closure_data);
typedef void (*Rtc__NodeRtts_Closure)
                 (const Rtc__NodeRtts *message,
                  void *closure_data);
typedef void (*Rtc__NodeRtt_Closure)
                 (const Rtc__NodeRtt *message,
                  void *closure_data);
typedef void (*Rtc__SelectChannel_Closure)
                 (const Rtc__SelectChannel *message,
                  void *closure_data);
typedef void (*Rtc__Stats_Closure)
                 (const Rtc__Stats *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    rtc__ice_policy__descriptor;
extern const ProtobufCEnumDescriptor    rtc__sdp_type__descriptor;
extern const ProtobufCEnumDescriptor    rtc__peer_state__descriptor;
extern const ProtobufCEnumDescriptor    rtc__close_reason__descriptor;
extern const ProtobufCEnumDescriptor    rtc__os_type__descriptor;
extern const ProtobufCEnumDescriptor    rtc__srtp_profile__descriptor;
extern const ProtobufCEnumDescriptor    rtc__channel__descriptor;
extern const ProtobufCEnumDescriptor    rtc__mode__descriptor;
extern const ProtobufCEnumDescriptor    rtc__source__descriptor;
extern const ProtobufCEnumDescriptor    rtc__direction__descriptor;
extern const ProtobufCEnumDescriptor    rtc__protocol__descriptor;
extern const ProtobufCEnumDescriptor    rtc__data_type__descriptor;
extern const ProtobufCMessageDescriptor rtc__signal_request__descriptor;
extern const ProtobufCMessageDescriptor rtc__signal_response__descriptor;
extern const ProtobufCMessageDescriptor rtc__rtc_config__descriptor;
extern const ProtobufCMessageDescriptor rtc__ice_server__descriptor;
extern const ProtobufCMessageDescriptor rtc__session_description__descriptor;
extern const ProtobufCMessageDescriptor rtc__subscribe__descriptor;
extern const ProtobufCMessageDescriptor rtc__subscribe__media__descriptor;
extern const ProtobufCMessageDescriptor rtc__subscribe__options__descriptor;
extern const ProtobufCMessageDescriptor rtc__add_track__descriptor;
extern const ProtobufCMessageDescriptor rtc__track_info__descriptor;
extern const ProtobufCMessageDescriptor rtc__remove_track__descriptor;
extern const ProtobufCMessageDescriptor rtc__state__descriptor;
extern const ProtobufCMessageDescriptor rtc__states__descriptor;
extern const ProtobufCMessageDescriptor rtc__options__descriptor;
extern const ProtobufCMessageDescriptor rtc__location__descriptor;
extern const ProtobufCMessageDescriptor rtc__joined__descriptor;
extern const ProtobufCMessageDescriptor rtc__leaved__descriptor;
extern const ProtobufCMessageDescriptor rtc__leave__descriptor;
extern const ProtobufCMessageDescriptor rtc__ping__descriptor;
extern const ProtobufCMessageDescriptor rtc__pong__descriptor;
extern const ProtobufCMessageDescriptor rtc__response__descriptor;
extern const ProtobufCMessageDescriptor rtc__vad__descriptor;
extern const ProtobufCMessageDescriptor rtc__volume__descriptor;
extern const ProtobufCMessageDescriptor rtc__broadcast__descriptor;
extern const ProtobufCMessageDescriptor rtc__mute__descriptor;
extern const ProtobufCMessageDescriptor rtc__mute__media__descriptor;
extern const ProtobufCMessageDescriptor rtc__peer_info__descriptor;
extern const ProtobufCMessageDescriptor rtc__srtp_key__descriptor;
extern const ProtobufCMessageDescriptor rtc__node_list__descriptor;
extern const ProtobufCMessageDescriptor rtc__node_rtts__descriptor;
extern const ProtobufCMessageDescriptor rtc__node_rtt__descriptor;
extern const ProtobufCMessageDescriptor rtc__select_channel__descriptor;
extern const ProtobufCMessageDescriptor rtc__stats__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_rtc_2frtc_2eproto__INCLUDED */
